# coding=utf-8
from app.customer.models.bottle_message import BottleMessageText


def add_bottle_message():
    anchor_text = [
        "Selam!",
        "Merhaba!",
        "Psst!",
        "Hey",
        "Selam güzelim",
        "Şşt fıstık!",
        "Naber",
        "Nasılsın?",
        "Nasıl gidiyor?",
        "Keyifler nasıl?",
        "Keyifler yerindedir umarım",
        "Selam canım",
        "Selam tatlım",
        "Selam müsait misin?",
        "Merhaba, müsait misin?",
        "Merhaba,sohbete var mısın?"
        "Seninle gerçekten sohbet etmek isterim",
        "Gerçekten sohbet etmeye değer birine benziyorsun",
        "Konuşalım mı canım sıkılıyor",
        "Çoookk sıkıldım!",
        "Sohbeti güzel birine benziyorsun",
        "Bu aralar havalar çok güzel",
        "Seninle tanışmak isterdim",
        "Tanışma fırsatımız olur mu ?",
        "Galiba bu uygulamadaki en güzel kızı buldum",
        "Galiba bu uygulamadaki en yakışıklı erkeği buldum",
        "Bu uygulamayı ne zamandır kullanıyorsun",
        "Nerelisin",
        "Kaç yaşındasın",
        "Napıyosun?",
        "Ne yapıyorsun?",
        "Sinemaya gidelim mi?",
        "Bu tatlılık sizde genetik mi?",
        "Bu hafta hava çok güzel",
        "Beni unuttun mu?",
        "Beni unutursan kalbimi kirarsin",
        "Çok yakışıklısın",
        "Çok güzelsin",
        "Ee daha daha nasılsın?",
        "Anlatsana bir şeyler",
        "Korkma ısırmam",
        "Neler yapmaktan hoşlanırsın",
        "Hobilerin neler?",
        "Yemek yapabilir misin",
        "En sevdiğin film ne ?",
        "En sevdiğin dizi ne? ",
        "Sevgilin var  mı ?",
        "Evli misin?",
        "Çok yoruldum, bir masaj fena olmazdı",
        "Bugün ne yemek yedin?",
        "Sigara içermisin?",
        "İçkiyle aran nasıl ?",
        "Boyun kaç?",
        "Ne iş yapıyorsun?",
        "Uzaklara çok uzaklara gitmek istiyorum bazen",
        "Bu aralar konuşacak birilerini bulmak çok zor",
        "Bunaldım bu hayattan",
        "Yüzmeyi severmisin?",
        "Balık tutmayı severmisin?",
        "En sevdiğin renk ne ?",
        "Hangi takımlısın? ",
        "Gezmeyi severmisin? Nerelere gittin? ",
        "Sesini duymak istiyorum",
        "Şarkı söyleyebiliyor musun?",
        "Yemek yedin mi? ",
        "Tatile ihtiyacım var",
        "Bir içkiye ihtiyacım var",
        "Bara gidelim mi? ",
        "En çok nerelere gitmeyi seversin?"
        ]
    user_text = [
        "Selam!",
        "Merhaba!",
        "Psst!",
        "Hey",
        "Selam güzelim",
        "Şşt fıstık!",
        "Naber",
        "Nasılsın?",
        "Nasıl gidiyor?",
        "Keyifler nasıl?",
        "Keyifler yerindedir umarım",
        "Selam canım",
        "Selam tatlım",
        "Selam müsait misin?",
        "Merhaba, müsait misin?",
        "Merhaba,sohbete var mısın?"
        "Seninle gerçekten sohbet etmek isterim",
        "Gerçekten sohbet etmeye değer birine benziyorsun",
        "Konuşalım mı canım sıkılıyor",
        "Çoookk sıkıldım!",
        "Sohbeti güzel birine benziyorsun",
        "Bu aralar havalar çok güzel",
        "Seninle tanışmak isterdim",
        "Tanışma fırsatımız olur mu ?",
        "Galiba bu uygulamadaki en güzel kızı buldum",
        "Galiba bu uygulamadaki en yakışıklı erkeği buldum",
        "Bu uygulamayı ne zamandır kullanıyorsun",
        "Nerelisin",
        "Kaç yaşındasın",
        "Napıyosun?",
        "Ne yapıyorsun?",
        "Sinemaya gidelim mi?",
        "Bu tatlılık sizde genetik mi?",
        "Bu hafta hava çok güzel",
        "Beni unuttun mu?",
        "Beni unutursan kalbimi kirarsin",
        "Çok yakışıklısın",
        "Çok güzelsin",
        "Ee daha daha nasılsın?",
        "Anlatsana bir şeyler",
        "Korkma ısırmam",
        "Neler yapmaktan hoşlanırsın",
        "Hobilerin neler?",
        "Yemek yapabilir misin",
        "En sevdiğin film ne ?",
        "En sevdiğin dizi ne? ",
        "Sevgilin var  mı ?",
        "Evli misin?",
        "Çok yoruldum, bir masaj fena olmazdı",
        "Bugün ne yemek yedin?",
        "Sigara içermisin?",
        "İçkiyle aran nasıl ?",
        "Boyun kaç?",
        "Ne iş yapıyorsun?",
        "Uzaklara çok uzaklara gitmek istiyorum bazen",
        "Bu aralar konuşacak birilerini bulmak çok zor",
        "Bunaldım bu hayattan",
        "Yüzmeyi severmisin?",
        "Balık tutmayı severmisin?",
        "En sevdiğin renk ne ?",
        "Hangi takımlısın? ",
        "Gezmeyi severmisin? Nerelere gittin? ",
        "Sesini duymak istiyorum",
        "Şarkı söyleyebiliyor musun?",
        "Yemek yedin mi? ",
        "Tatile ihtiyacım var",
        "Bir içkiye ihtiyacım var",
        "Bara gidelim mi? ",
        "En çok nerelere gitmeyi seversin?"
    ]
    label = 0
    for text in anchor_text:
        label += 1
        BottleMessageText.create_message_text(label, text, 0, 1)

    label = 3000

    for text in user_text:
        label += 1
        BottleMessageText.create_message_text(label, text, 1, 2)
